C#/SpotifyChangeControl/SpotifyChangeControlASPCore/Controllers/ChangesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Mvc.Client.Models.Changes;
// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
using System.Security.Claims;
using SpotifyChangeControlLib.DataObjects;
using System.Web;

namespace Mvc.Client.Controllers
{
    
    public class ChangesController : Controller
    {
        private SpotifyChangeControlLib.SCCManager _oSCCManager;
        public ChangesController()
        {
            this._oSCCManager = new SpotifyChangeControlLib.SCCManager();
        }


        [Route("Changes/Index")]
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        //[Route("~/Changes/Search")]
        [Route("Changes/Search")]
        [HttpGet]
        public IActionResult Search()
        {
            return View(new SearchModel());
        }

        [Route("Changes/Results")]
        [HttpGet]
        public IActionResult Results([Bind]SearchModel oSearchModel)
        {
            try
            {
                //ResultModel oResultModel = new ResultModel();
                //oResultModel.Start = oSearchModel.Start;
                //oResultModel.End = oSearchModel.End;
                IEnumerable<Claim> oClaims = User.FindAll("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier");
                long iUserID = 0;
                foreach (Claim oClaim in oClaims)
                {
                    iUserID = this._oSCCManager.GetObjectIDForSpotifyID(oClaim.Value);
                }

                IEnumerable<SpotifyPlaylistChange> oPlaylistChanges = this._oSCCManager.GetPlaylistChangesForUser(iUserID, oSearchModel.Start.Value, oSearchModel.End.Value);
                return View("Results", new ResultModel(oSearchModel, oPlaylistChanges));
            }
            catch (Exception)
            {
                return new RedirectResult("~/Errors/GetCustomErrorPageToMakeTheStupidHumanFeelGoodAboutThereTecnicalAbilitiesAndReassureThemItsNotTheirFault?sHttpStatus=500");
            }
        }

        
    }
}

C#/SpotifyChangeControl/SpotifyChangeControlASPCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>SpotifyChangeControl</title>

    <link href="~/stylesheets/bootstrap.min.css" rel="stylesheet" />
    <link href="~/stylesheets/jumbotron-narrow.css" rel="stylesheet" />
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>

<body>



    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                </div>
                <div class="modal-body">
                    This is my modal
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>




    <div class="navbar navbar-inverse ">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Spotify Change Control", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">W5H<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("What", "What", "Home")</li>
                            <li>@Html.ActionLink("Why", "Why", "Home")</li>
                            <li>@Html.ActionLink("Who", "Who", "Home")</li>
                            <li>@Html.ActionLink("Where", "Where", "Home")</li>
                            <li>@Html.ActionLink("When", "When", "Home")</li>
                            <li>@Html.ActionLink("How", "How", "Home")</li>
                            <li>@Html.ActionLink("FAQ", "FAQ", "Home")</li>
                        </ul>
                    </li>
                    @if (User?.Identity?.IsAuthenticated ?? false)
                    {
                        <li>@Html.ActionLink("Search", "Search", "Changes")</li>
                    }
                   
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container">


        @RenderBody()
        
        <div class="footer">
            <p>&copy; @DateTime.Now.Year JorDang Industries LLC</p>
        </div>

    </div>
</body>
</html>